[package]
name = "todo-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
todo-core = { path = "../todo-core" }
tokio = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
